name: [DEPRECATED] Auto PR

on: {}

jobs:
  deprecated:
    name: Workflow deprecated
    runs-on: ubuntu-latest
    steps:
      - name: Warning
        run: echo "⚠️ Ce workflow est obsolète et ne fait plus rien. Les PR sont gérées par l'agent externe."
