name: [DEPRECATED] Auto PR

on: {}

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Warning
        run: echo "⚠️ Ce workflow est obsolète et ne fait rien. Les PR sont gérées par l'agent externe."
