name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean web dependencies
        working-directory: ./web
        run: |
          rm -f package-lock.json
          npm cache clean --force

      - name: Install web dependencies
        working-directory: ./web
        run: npm install --no-audit --no-fund

      - name: Lint web
        working-directory: ./web
        run: npm run lint

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint backend
        working-directory: ./backend
        run: |
          pip install black isort flake8
          black --check .
          isort --check .
          flake8 .

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Get mobile dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Analyze mobile
        working-directory: ./mobile
        run: flutter analyze
