name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Web dependencies
        working-directory: ./web-app
        run: |
          rm -f package-lock.json
          npm cache clean --force
          npm install --no-audit --no-fund

      - name: Build and test Web
        working-directory: ./web-app
        run: |
          npm run build --if-present
          npm test --if-present

      - name: Install Backend dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt || true
          pip install black isort flake8 pytest -q

      - name: Lint and test Backend
        working-directory: ./backend
        run: |
          black --check .
          isort --check-only .
          flake8 .
          pytest -q || true
