name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install --upgrade pip
          pip install -e ".[test]"

      - name: Run backend tests
        working-directory: ./backend
        run: pytest --cov=backend --cov-report=term-missing

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install web dependencies
        working-directory: ./web
        run: npm install

      - name: Lint web
        working-directory: ./web
        run: npm run lint

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Get mobile dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Analyze mobile
        working-directory: ./mobile
        run: flutter analyze
