name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Tests (non-bloquants)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install web dependencies
        working-directory: ./web
        run: npm install --no-audit --no-fund || true

      - name: Lint web
        working-directory: ./web
        run: npm run lint || true

      - name: Build web
        working-directory: ./web
        run: npm run build || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install --upgrade pip || true
          pip install -r requirements.txt || true

      - name: Lint backend
        working-directory: ./backend
        run: |
          pip install black isort flake8 || true
          black --check . || true
          isort --check . || true
          flake8 . || true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Get mobile dependencies
        working-directory: ./mobile
        run: flutter pub get || true

      - name: Analyze mobile
        working-directory: ./mobile
        run: flutter analyze || true
