name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean and install web dependencies
        working-directory: ./web
        run: |
          rm -f package-lock.json
          npm cache clean --force
          npm install --no-audit --no-fund
          npm run build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest

      - name: Lint and test backend
        working-directory: ./backend
        run: |
          black --check .
          isort --check .
          flake8 .
          pytest
