name: Deploy PROD

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'

env:
  ENVIRONMENT: production

jobs:
  deploy:
    name: Deploy to Raspberry Pi (PROD)
    runs-on: [self-hosted, pi, prod]
    environment:
      name: production
      url: https://${{ secrets.PROD_DOMAIN }}
    steps:
      - uses: actions/checkout@v4

      - name: Load env file
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env
          cat .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml push

      - name: Deploy
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh prod ${{ github.ref_name || inputs.version }}
